# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-08-31 17:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_file', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tweet',
            name='url',
            field=models.CharField(default='https://twitter.com/', max_length=500),
        ),
    ]
